# Reproducibility

As you learn more about neural networks and machine learning, you'll start to discover how much randomness plays a part.

Well, pseudorandomness that is. Because after all, as they're designed, a computer is fundamentally deterministic, so the randomness they create is *simulated* randomness.

To reduce the impact of this randomness in neural networks, the concept of  a random seed is introduced. A random seed is a number that initializes the pseudorandom number generator (PRNG) in a way that allows you to reproduce the same sequence of random numbers.

In [1]:
import torch

Let's create two random tensors $A$ and $B$:

In [2]:
A = torch.rand(3, 4)
B = torch.rand(3, 4)

print(A)
print(B)
print(A == B)

tensor([[0.1686, 0.2384, 0.7052, 0.5539],
        [0.8363, 0.9141, 0.2177, 0.0435],
        [0.1069, 0.5115, 0.9120, 0.0212]])
tensor([[0.7591, 0.9431, 0.4685, 0.4815],
        [0.5604, 0.0890, 0.0408, 0.1474],
        [0.1263, 0.4771, 0.4094, 0.4718]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


It is highly unlikely that the two tensors will be the same, which will make it difficult to reproduce results. Let's set a random seed and create the tensors again:

In [6]:
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
C = torch.rand(3, 4)
# torch.manual_seed() has to be called before every random generator
torch.manual_seed(RANDOM_SEED)
D = torch.rand(3, 4)

print(C)
print(D)
print(C == D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Deterministic operations are often slower than nondeterministic operations, so single-run performance may decrease for your model. However, determinism may save time in development by facilitating experimentation, debugging, and regression testing.