# Reproducibility

As you learn more about neural networks and machine learning, you'll start to discover how much randomness plays a part.

Well, pseudorandomness that is. Because after all, as they're designed, a computer is fundamentally deterministic, so the randomness they create is *simulated* randomness.

To reduce the impact of this randomness in neural networks, the concept of  a random seed is introduced. A random seed is a number that initializes the pseudorandom number generator (PRNG) in a way that allows you to reproduce the same sequence of random numbers.

In [1]:
import torch

Let's create two random tensors $A$ and $B$:

In [2]:
A = torch.rand(3, 4)
B = torch.rand(3, 4)

print(A)
print(B)
print(A == B)

tensor([[0.3222, 0.3425, 0.9287, 0.9645],
        [0.9655, 0.7451, 0.2176, 0.3717],
        [0.2267, 0.1199, 0.4297, 0.5454]])
tensor([[0.9668, 0.2431, 0.2669, 0.6166],
        [0.0928, 0.9545, 0.5554, 0.1434],
        [0.4719, 0.1920, 0.7063, 0.8740]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


It is highly unlikely that the two tensors will be the same, which will make it difficult to reproduce results. Let's set a random seed and create the tensors again:

In [3]:
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
C = torch.rand(3, 4)
# torch.manual_seed() has to be called before every random generator
torch.manual_seed(RANDOM_SEED)
D = torch.rand(3, 4)

print(C)
print(D)
print(C == D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Deterministic operations are often slower than nondeterministic operations, so single-run performance may decrease for your model. However, determinism may save time in development by facilitating experimentation, debugging, and regression testing.